# Generated by Django 5.0 on 2023-12-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='brief',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='img',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='img',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
