# Generated by Django 5.0 on 2023-12-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_img_brief_img_sub_title_img_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
