# Generated by Django 5.0 on 2023-12-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_img_sub_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Img',
            new_name='why_us',
        ),
    ]
