# Generated by Django 5.0 on 2023-12-13 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='img1',
            new_name='image',
        ),
    ]
