# Generated by Django 5.0 on 2023-12-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_img1_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='text3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
